print("Hello World!")
print("I am a good boy")
print("This is the first file of Rebol Langugae for testing Hello World!")
print("You can see that the print function of Rebol Language is very similar to Python Programming Language.")
print(5+5)
print("You can add these numbers directly by using a sum sign between them and displaying the result with the help of print function.")
print("You can also do other mathematical operations just like we did the sum.")
print(10-5)
print(10*10)
print(10/2)
print("Clone this file and practice this function by yourself. Believe Me! it's very easy.")
